### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by seventhsite** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#187] opened 2022-06-20 15:42 UTC
Hi! I give this error when trying to backup my FortiGate config. My playbook

```
- hosts: fortigates
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    vdom: "root"
  tasks:
  - name: Backup
    fortios_export_config_playbook:
      access_token: "{{ fortios_access_token }}"
      selector: system_global
      output_path: "./test.backup"
```

```
The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-local-201337hpcpy_fb/ansible-tmp-1655739263.7023761-201408-150805982554431/AnsiballZ_fortios_export_config_playbook.py", line 102, in <module>
    _ansiballz_main()
  File "/home/vagrant/.ansible/tmp/ansible-local-201337hpcpy_fb/ansible-tmp-1655739263.7023761-201408-150805982554431/AnsiballZ_fortios_export_config_playbook.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vagrant/.ansible/tmp/ansible-local-201337hpcpy_fb/ansible-tmp-1655739263.7023761-201408-150805982554431/AnsiballZ_fortios_export_config_playbook.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_export_config_playbook', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_fortios_export_config_playbook_payload_5bwl5zvd/ansible_fortios_export_config_playbook_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_export_config_playbook.py", line 6112, in <module>
  File "/tmp/ansible_fortios_export_config_playbook_payload_5bwl5zvd/ansible_fortios_export_config_playbook_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_export_config_playbook.py", line 6074, in main
  File "/tmp/ansible_fortios_export_config_playbook_payload_5bwl5zvd/ansible_fortios_export_config_playbook_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_export_config_playbook.py", line 4619, in fortios_configuration_fact
  File "/tmp/ansible_fortios_export_config_playbook_payload_5bwl5zvd/ansible_fortios_export_config_playbook_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_export_config_playbook.py", line 4624, in <listcomp>
AttributeError: 'str' object has no attribute 'items'
fatal: [forti_1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-local-201337hpcpy_fb/ansible-tmp-1655739263.7023761-201408-150805982554431/AnsiballZ_fortios_export_config_playbook.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-local-201337hpcpy_fb/ansible-tmp-1655739263.7023761-201408-150805982554431/AnsiballZ_fortios_export_config_playbook.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-local-201337hpcpy_fb/ansible-tmp-1655739263.7023761-201408-150805982554431/AnsiballZ_fortios_export_config_playbook.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_export_config_playbook', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_export_config_playbook_payload_5bwl5zvd/ansible_fortios_export_config_playbook_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_export_config_playbook.py\", line 6112, in <module>\n  File \"/tmp/ansible_fortios_export_config_playbook_payload_5bwl5zvd/ansible_fortios_export_config_playbook_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_export_config_playbook.py\", line 6074, in main\n  File \"/tmp/ansible_fortios_export_config_playbook_payload_5bwl5zvd/ansible_fortios_export_config_playbook_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_export_config_playbook.py\", line 4619, in fortios_configuration_fact\n  File \"/tmp/ansible_fortios_export_config_playbook_payload_5bwl5zvd/ansible_fortios_export_config_playbook_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_export_config_playbook.py\", line 4624, in <listcomp>\nAttributeError: 'str' object has no attribute 'items'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by JieX19** [comment] 2022-06-21 00:00
@seventhsite 

I can reproduce the error. It's caused by the inconsistent data type from the backend and the RESTAPI definitions. Backend returns a string for some params that accept multiple values, while RESTAPI actually accepts a list to save these values. 

I will fix the issue in the next release and will inform you once it's released.

Thanks!

**Comment by JieX19** [comment] 2024-01-04 23:50
Hi @seventhsite 

The issue has been fixed in the collection. I will close the issue at this moment, marking it as resolved or completed. If you have any further questions or concerns, please feel free to reopen the ticket or create a new one.

**Closed by JieX19** 2024-01-04 23:50 UTC
Labels: bug
