### ISSUE TITLE
Create vlan interface in VDOM

### ISSUE THREAD

**Issue by Superset1986** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#104] opened 2021-05-03 10:59 UTC
Hi,

I'm unable to create a vlan interface when the "main" interface belongs to a different vdom.   If I create the vlan interface in the same vdom as the "main interface" it works perfectly. The API user has full permissions to all vdoms.

**Playbook:**

tasks:

- name: Configure interfaces.

fortios_system_interface:

vdom: "{{ item.vdom }}"

state: "present"

access_token: "{{ fortios_access_token }}"

system_interface:

name: "{{ item.name }}"

role: "{{ item.role }}"

ip: "{{ item.ip }}"

vlanid: "{{ item.vlan }}"

interface: "{{ item.interface }}"

description: "{{ item.desc }}"

allowaccess: "{{ item.acc }}"

device_identification: enable

vdom: "{{ item.vdom }}"

with_items:

- "{{ Variables }}"

**Full error:**

: {"build": 5653, "cli_error": "current vf=vdom-xxx:3\nentry not found in datasource\nAttribute 'interface' value 'interfaceXX' checking fail -3\nCommand fail. Return code -3\nCommand fail. Return code 1\n", "error": -3, "http_method": "POST", "http_status": 500, "name": "interface", "old_revision": "3d35b0eda2dffd9b6803cdd2f0d93a75", "path": "system", "revision": "a96a11d5a6f01acc8cb77f2b1cb64679", "revision_changed": true, "serial": "xxxxxxxxxxxx", "status": "error", "vdom": "vdom-xxx", "version": "v6.4.5"}, "msg": "Error in repo"}

**Comment by JieX19** [comment] 2021-05-11 18:11
Hi @Superset1986,

Can you please provide me the **'Variables'** param? 

If possible, can you please provide me the debugging log?
Verbose output can help with debugging. To enable verbose debugging, use the following commands in the FortiGate CLI:

**diagnose debug enable
diagnose debug application httpsd -1**

**Comment by pebcakit** [comment] 2021-06-11 17:09
I may be hitting the same issue with vlan and redundant interfaces.

The problem is that if you set  `name:`  using an interface that does not exist on the firewall yet, it would return: Object with mkey TEST_VLAN not found and allow_append flag not set.

The only workaround I found is to use the raw module for this, which is less than ideal.

`[httpsd 591 - 1623430840     info] fweb_debug_init[302] -- New PUT request for "/api/v2/cmdb/system/interface/TEST_VLAN" from "x.x.x.x:xxxx"
[httpsd 591 - 1623430840     info] fweb_debug_init[303] -- User-Agent: "Python-urllib/3.9"
[httpsd 591 - 1623430840     info] fweb_debug_init[305] -- Handler "api_cmdb_v2-handler" assigned to request
[httpsd 591 - 1623430840     info] aps_init_process_vdom[1290] -- initialized process vdom to 'root' (cookie='(null)')
[httpsd 591 - 1623430840     info] api_store_parameter[239] -- add API parameter 'vdom' (type=string)
[httpsd 591 - 1623430840     info] api_store_parameter[239] -- add API parameter 'allowaccess' (type=string)
[httpsd 591 - 1623430840     info] api_store_parameter[239] -- add API parameter 'interface' (type=string)
[httpsd 591 - 1623430840     info] api_store_parameter[239] -- add API parameter 'ip' (type=string)
[httpsd 591 - 1623430840     info] api_store_parameter[239] -- add API parameter 'mode' (type=string)
[httpsd 591 - 1623430840     info] api_store_parameter[239] -- add API parameter 'name' (type=string)
[httpsd 591 - 1623430840     info] api_store_parameter[239] -- add API parameter 'type' (type=string)
[httpsd 591 - 1623430840     info] api_store_parameter[239] -- add API parameter 'vlanid' (type=int)
[httpsd 591 - 1623430840     info] handle_cli_req_v2_vdom[2148] -- new CMDB API request (vdom='root',user='admin')
[httpsd 591 - 1623430840     info] api_cmdb_request_init_by_path[1517] -- new CMDB query (path='system',name='interface')
[httpsd 591 - 1623430840     info] api_cmdb_request_init_by_path[1546] -- querying CMDB entry (mkey='TEST_VLAN')
[httpsd 591 - 1623430840     info] api_cmdb_request_init_by_path[1550] -- unable to find 'TEST_VLAN' in table 'system.interface'
[httpsd 591 - 1623430840    error] _api_cmdb_v2_config[1141] -- Object with mkey TEST_VLAN not found and allow_append flag not set
[httpsd 591 - 1623430840  warning] api_return_http_result[696] -- API error 404 raised
[httpsd 591 - 1623430840     info] fweb_debug_final[203] -- Completed PUT request for "/api/v2/cmdb/system/interface/TEST_VLAN" (HTTP 404)`

**Comment by JieX19** [comment] 2021-09-13 21:01
Hi @Superset1986 

Feel free to open an issue if you still have any questions on this module.

Thanks!

**Closed by JieX19** 2021-09-13 21:01 UTC
